// Pure math-quiz scoring — no I/O, no socket, no DB.
// Solo numeric-input quiz: each problem is generated by mathgen.ts and carries
// its own truth (`answer`) plus a scoring band (`tol`/`range`). The client
// submits typed numeric guesses; the server re-scores them here.
//
// Linear-band scoring: full credit within `tol` of the answer, linear decay to
// zero at `range`, zero beyond. Exact (true/false) scoring is the degenerate
// case `range === tol` — a step function.

export const QUESTION_COUNT = 10;
export const TIMER_MS = 45000; // calculus problems need more time than MCQ
export const BASE_POINTS = 10;

export type Outcome = 'correct' | 'partial' | 'wrong' | 'skip';

export interface ScorableProblem {
  answer: number;
  scoring: 'exact' | 'proximity';
  tol: number;
  range: number;
  points: number;
  // Optional near-exact bonus: if the guess lands within `bonusTol` of the
  // answer, add `bonus` points on top of full credit. Used by proximity
  // problems (e.g. sqrt-estimate) to reward a (near-)perfect answer.
  bonus?: number;
  bonusTol?: number;
}

// Score a single guess against one problem's band.
// guess === null means skip / timeout / unparseable input → 0 points.
export function scorePick(
  p: ScorableProblem,
  guess: number | null,
): { earned: number; fraction: number; outcome: Outcome; bonus: boolean } {
  if (guess === null || guess === undefined || Number.isNaN(guess)) {
    return { earned: 0, fraction: 0, outcome: 'skip', bonus: false };
  }
  const d = Math.abs(guess - p.answer);
  let fraction: number;
  if (d <= p.tol) {
    fraction = 1;
  } else if (d >= p.range) {
    fraction = 0;
  } else {
    // p.range > p.tol guaranteed here (the two branches above cover equality)
    fraction = (p.range - d) / (p.range - p.tol);
  }
  let earned = Math.round(p.points * fraction);
  let bonus = false;
  if (p.bonus && p.bonusTol !== undefined && d <= p.bonusTol) {
    earned += p.bonus;
    bonus = true;
  }
  const outcome: Outcome = fraction === 1 ? 'correct' : fraction === 0 ? 'wrong' : 'partial';
  return { earned, fraction, outcome, bonus };
}

// Re-score a finished run. `guesses[i]` is the parsed value the client reported
// for problem i (null = skip/timeout).
export function scorePicks(
  problems: ScorableProblem[],
  guesses: (number | null)[],
): { score: number; results: Outcome[]; earned: number[] } {
  let score = 0;
  const results: Outcome[] = [];
  const earned: number[] = [];
  for (let i = 0; i < problems.length; i++) {
    const r = scorePick(problems[i], guesses[i]);
    score += r.earned;
    results.push(r.outcome);
    earned.push(r.earned);
  }
  return { score, results, earned };
}
